[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[background]
fit = "Cover"
path = "/run/media/SDCARD/Wallpapers/Lockscreen/42nakedfinal2.png"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
icon_theme_name = "Adwaita"
theme_name = "Materia"
font_name = "Noto Sans 16"
