set tabstop=4
set shiftwidth=4
set background=dark
set autoindent
set number
set ruler
set rulerformat=%l-%v
set mouse=a
let g:user42 = 'fclivaz'
let g:mail42 = 'fclivaz@student.42lausanne.ch'
syntax enable
