# Please note not all available settings / options are set here.
# For a full list, see the wiki

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-1, 3840x2160@120, 0x0, 1.666

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch

# Source a file (multi-file configs)
source = ~/.config/hypr/_hyprexec.conf
source = ~/.config/hypr/_hyprbind.conf
source = ~/.config/hypr/_hyprrule.conf
source = ~/.config/hypr/_hypranim.conf
source = ~/.config/hypr/_hyprdeco.conf
source = ~/.config/hypr/_hyprplug.conf

# Set programs that you use
$terminal = kitty
$files = nautilus -w
$menu = wofi 

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct # change to qt6ct if you have that
env = GTK_THEME,Materia:dark
env = LIBVA_DRIVER_NAME,radeonsi
# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
	numlock_by_default = true

    follow_mouse = 1
	repeat_delay = 300
	repeat_rate = 50
	float_switch_override_focus = 0
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 4
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(33ccffff) rgba(00ff99ff) 45deg
    col.inactive_border = rgba(AAAAAAaa) rgba(595959aa) 45deg


    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
