# Config for Hyprland decorations

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 14
	active_opacity = 1
	inactive_opacity = 0.85
    blur {
        enabled = true
		ignore_opacity = false
        size = 6
        passes = 1
		noise = 0.085
	}
	dim_inactive = false
    drop_shadow = no
    shadow_range = 4
    shadow_render_power = 1
    col.shadow = rgba(1a1a1aee)
}

# blurls = waybar

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_status = master
	new_on_top = true
}
