[font]
size = 11
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGMDZ Nerd Font", style = "Bold Italic" }
builtin_box_drawing = true
glyph_offset = { x = 0, y = -1 }
