[colors]
    draw_bold_text_with_bright_colors = false

[env]
    TERM = "xterm-256color"

[window]
blur = true
opacity = 0.8
dynamic_padding = false

[general]
live_config_reload = true
import = ["themes/xterm.toml", "_font.toml"]

[keyboard]
bindings = [
   { key = "Space", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[scrolling]
history = 16384

[bell]
command = { program = "ffplay", args = ["-nodisp", "/usr/share/sounds/freedesktop/stereo/bell.oga", "-autoexit", "-volume", "15"] }
