[colors]
    draw_bold_text_with_bright_colors = false

[env]
    TERM = "xterm-256color"

[window]
blur = true
opacity = 0.85
dynamic_padding = false

[font]
size = 11
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGMDZ Nerd Font", style = "Bold Italic" }
glyph_offset = { x = 0, y = -1 }
builtin_box_drawing = true

[general]
live_config_reload = true
import = ["themes/xterm.toml"]

[keyboard]
bindings = [
   { key = "Space", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[scrolling]
history = 16384

[bell]
command = { program = "ffplay", args = ["-nodisp", "/usr/share/sounds/freedesktop/stereo/bell.oga", "-autoexit"] }
