--structure "Title:Separator:OS:Host:Kernel:Uptime:Packages:Shell:Display:Terminal:CPU:GPU:Memory:Disk:Break:Colors"
--host-format "{/2}{-}{/}{2}{?3} {3}{?}"
--os-format "{3} {12}"
--display-key Resolution
--display-compact-type original
--memory-format "{/1}{-}{/}{/2}{-}{/}{} / {}"
--logo-color-1 "94"
--color-keys 94
--color-title 94
